### ISSUE TITLE
Using TimeML-Normalizer as a maven dependency?

### ISSUE THREAD

**Issue by powpos360** [hllorens/timeml-normalizer#2]
Hi @hllorens, is it possible to use this as a maven dependency? It doesn't seem to be in your release. Thanks!

**Comment by hllorens** [comment]
Hi @666666fzl, it is not updated to any maven repo so the answer is no.
Solutions:
1) You add is as a maven "local" dependency from a lib/ folder or so
2) You update it to a maven repo and use it from there (maybe you could contribute that to this project and share the url here).

Thanks
Hector
